# SPDX-License-Identifier: Apache-2.0
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
# Any modifications Copyright OpenSearch Contributors. See
# GitHub history for details.

# This list contains paths to models that we want to exclude from model listing
# generated by update_pretrained_model_listing.py in "Model Listing Workflow I: Updating" workflow
EXCLUDED_MODELS = [
    "ml-models/huggingface/sentence-transformers/all-MiniLM-L12-v2/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/all-MiniLM-L12-v2/1.0.0/torch_script",
    "ml-models/huggingface/sentence-transformers/all-MiniLM-L6-v2/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/all-MiniLM-L6-v2/1.0.0/torch_script",
    "ml-models/huggingface/sentence-transformers/all-distilroberta-v1/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/all-distilroberta-v1/1.0.0/torch_script",
    "ml-models/huggingface/sentence-transformers/all-mpnet-base-v2/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/all-mpnet-base-v2/1.0.0/torch_script",
    "ml-models/huggingface/sentence-transformers/msmarco-distilbert-base-tas-b/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/msmarco-distilbert-base-tas-b/1.0.0/torch_script",
    "ml-models/huggingface/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/multi-qa-MiniLM-L6-cos-v1/1.0.0/torch_script",
    "ml-models/huggingface/sentence-transformers/multi-qa-mpnet-base-dot-v1/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/multi-qa-mpnet-base-dot-v1/1.0.0/torch_script",
    "ml-models/huggingface/sentence-transformers/paraphrase-MiniLM-L3-v2/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/paraphrase-MiniLM-L3-v2/1.0.0/torch_script",
    "ml-models/huggingface/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/1.0.0/onnx",
    "ml-models/huggingface/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/1.0.0/torch_script",
]
