name: Delete merged branch for model-uploader & model-listing-uploader 
on: 
  pull_request:
    types:
      - closed
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref,'model-uploader/') || startsWith(github.event.pull_request.head.ref,'model-listing-uploader/')
    steps:
      # Compared to backport.yml, this GitHub action will delete branch
      # of a PR that is closed, but not merged as well.
      - name: Delete closed PR branch
        uses: dawidd6/action-delete-branch@v4
        with:
          GITHUB_TOKEN: ${{github.token}}
          numbers: ${{github.event.pull_request.number}}
